### PR TITLE
Added AWS cli spoon.me file

### PR DESCRIPTION
**Pull request by gamlerhart**
No version grabing. Website doesn't seem to have any version declared?

### CODE REVIEW

**Comment by pgalisz** [comment]
in such case normally we use python/powershell to get version from executable :)

**Comment by gamlerhart** [comment]
Ok...will peek into that. =)

**Comment by pgalisz** [comment]
examples:
chocolatey, flash, for wordpress  we read it from readme :) We have python/powershell so every place can by used

**Comment by gamlerhart** [comment]
Added version grabbing.

**Comment by pgalisz** [comment]
merged, thx!

**Pull request merged**
